### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by cbuffalino** [supermamon/scriptable-scripts#1]
![6B11B066-F355-453D-9643-59ADAEFC83E5](https://user-images.githubusercontent.com/74877293/99915612-87920e00-2cb9-11eb-8d34-1bfaf2ba13db.png)

Unsure what this error is referencing. I did not modify the code under the username area. I believe all usernames are correctly spelled. Maybe you could shed some light?

**Comment by supermamon** [comment]
would you mind sharing the usernames, if possible?

**Comment by cbuffalino** [comment]
Best regards,

Chris Buffalino
Cbuffalino@gmail.com

On Nov 24, 2020, at 4:57 AM, Raymond Velasquez <notifications@github.com> wrote:

﻿
would you mind sharing the usernames, if possible?

**Comment by supermamon** [comment]
Did you mean to show the usernames? If you replied by mail and embedded a screenshot, github did not include the screenshot.

**Comment by cbuffalino** [comment]
No it was this photo:




Best regards,

Chris Buffalino
Cbuffalino@gmail.com

On Nov 26, 2020, at 8:18 AM, Raymond Velasquez <notifications@github.com> wrote:

﻿
Did you mean to show the usernames? If you replied by mail and embedded a screenshot, github did not include the screenshot.

**Comment by supermamon** [comment]
@cbuffalino,

Photos don't appear on github when you reply by email. Reply on the github website itself.
