### ISSUE TITLE
Data could be read because it’s not in the correct format

### ISSUE THREAD

**Issue by cbuffalino** [supermamon/scriptable-scripts#3]
Over the last two days the widget has stopped running all together. All I get is a black box that says “the data couldn’t be read because it isn’t in the correct format”

Updated to 1.3 same issue copied directly from GH and also tried downloading directly from scriptable gallery without adding any of my own users or making any changes to the script whatsoever. 

Attached photo is from a direct copy paste from git
![C4A764E7-4D5A-45C4-81D2-728E01537748](https://user-images.githubusercontent.com/74877293/100373297-697d2400-2fbf-11eb-921e-1eceed9ab9a9.png)

**Comment by supermamon** [comment]
See #2

**Comment by cbuffalino** [comment]
Thanks man. Happy thanksgiving, if you celebrate. 



Best regards,

Chris Buffalino
Cbuffalino@gmail.com

On Nov 26, 2020, at 8:16 AM, Raymond Velasquez <notifications@github.com> wrote:

﻿
See #2
