### ISSUE TITLE
Error on widget, "the data could not be read"

### ISSUE THREAD

**Issue by lomarence** [supermamon/scriptable-scripts#4]
So I got a weird error on the widget. It says: "The data couldn't be read because it isn't in the correct format" I reloaded the source code from your site and didn't change anything, not even the Instagram accounts.

Do you know whats going on there? Did Instagram changed something on their side?

**Comment by 98percent** [comment]
I have same problem with this widget. 
It would be very happy if anybody solve the issue.

**Comment by blacksector** [comment]
I had the same issue, I think it is related to rate limiting on Instagram's side. I switched from WiFi to Data and reloaded the widget and that did the trick

**Comment by supermamon** [comment]
This is fixed. Please see the updated code on the new repo - https://github.com/supermamon/scriptable-instagram-widgets
