### ISSUE TITLE
Error on Instagram Latest Posts

### ISSUE THREAD

**Issue by marcoPL2310** [supermamon/scriptable-scripts#6]
since some days I can't use the script. 

"Error on line 464:28: TypeError:
undefined is not an object (evaluating
'resp.graphql.shortcode_media')"

Can you help?
Thank you

**Comment by supermamon** [comment]
Trying going into the `/Scriptable/cache/igclient` folder and delete the `session.json` file.
 Then run the script inside the app. It should prompt you to re-login to Instagram.

**Comment by marcoPL2310** [comment]
I deleted the file and run the script. I re-login to Instagram. 
Same error.

I think the problem is since Instagram was down...

**Comment by marcoPL2310** [comment]
Now it works 👍🏻
